// This file is automatically generated and contains assets from celo-alfajores.
// Generate for other networks by running: yarn generate-assets [network].
// Supported networks are: arbitrum, goerli, mainnet, and polygon.

import { Address } from '@graphprotocol/graph-ts';

class Assets {
  public stableAssets: Address[];
  public pricingAssets: Address[];
  public fxAssetAggregators: Address[][];
}

export const tcUSD_ADDRESS = Address.fromString('0x51f29e07c7cf53D2603e1A224E27b1c74E181a17');
export const USDC_ADDRESS = Address.fromString('0x9A3a52f4462585c31025e2242C9b4074a9FB4a1f');

export const assets: Assets = {
  stableAssets: [
    Address.fromString('0x51f29e07c7cf53D2603e1A224E27b1c74E181a17'), // tcUSD
    Address.fromString('0x9A3a52f4462585c31025e2242C9b4074a9FB4a1f'), // tUSDC
  ],
  pricingAssets: [
    Address.fromString('0xE036290F41c367AeC59aec5B69C2B72068C441f6'), // tCELO
    Address.fromString('0x68DF333c5F5835A186AA8bCe4a704432006fDF49'), // tREGEN
  ],
  fxAssetAggregators: [],
};
